In [1]:
import torch 

In [2]:
a = torch.ones((4,5))

In [3]:
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [16]:
cat_a1 = torch.cat([a,a],dim=0)

In [17]:
cat_a1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
b = torch.ones((4,5))
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
cat_ab = torch.cat([a,b],dim=0)
cat_ab

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
// dim = 1 时是横向cat
cat_a2= torch.cat([a,a],dim=1)

In [19]:
cat_a2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
a = torch.normal(0,1,(3,4))
a

tensor([[ 1.0421,  0.8323,  0.0422,  0.2046],
        [-0.8536,  0.3113, -0.6995, -2.0206],
        [-0.3579,  1.0506,  0.0785,  0.0732]])

In [21]:
b = torch.normal(0,1,(3,4))
b

tensor([[ 0.0814,  0.7252, -1.2259, -0.2123],
        [ 0.0816,  0.2502, -0.0657,  0.6127],
        [ 0.6372, -0.5943, -1.4016,  0.3673]])

In [22]:
stat_ab = torch.stack([a,b],dim=0)

In [23]:
stat_ab

tensor([[[ 1.0421,  0.8323,  0.0422,  0.2046],
         [-0.8536,  0.3113, -0.6995, -2.0206],
         [-0.3579,  1.0506,  0.0785,  0.0732]],

        [[ 0.0814,  0.7252, -1.2259, -0.2123],
         [ 0.0816,  0.2502, -0.0657,  0.6127],
         [ 0.6372, -0.5943, -1.4016,  0.3673]]])

In [27]:
stack_ab1 = torch.stack([a,b],dim=2)


In [28]:
stack_ab1

tensor([[[ 1.0421,  0.0814],
         [ 0.8323,  0.7252],
         [ 0.0422, -1.2259],
         [ 0.2046, -0.2123]],

        [[-0.8536,  0.0816],
         [ 0.3113,  0.2502],
         [-0.6995, -0.0657],
         [-2.0206,  0.6127]],

        [[-0.3579,  0.6372],
         [ 1.0506, -0.5943],
         [ 0.0785, -1.4016],
         [ 0.0732,  0.3673]]])

In [35]:
ca = torch.ones((3,7))
ch_a = torch.chunk(ca,3,1)

In [36]:
ch_a

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [33]:
sa = torch.ones((3,7))
sp_sa = torch.split(sa,4,1)
sp_sa

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [34]:
sa

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [38]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [39]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [40]:
idx = torch.tensor([0,2])

In [41]:
idx

tensor([0, 2])

In [42]:
res = torch.index_select(points,dim=0,index=idx)

In [43]:
res 

tensor([[4., 1.],
        [2., 1.]])

In [44]:
mask = points.ge(3)

In [45]:
mask

tensor([[ True, False],
        [ True,  True],
        [False, False]])

In [46]:
res1 = torch.masked_select(points,mask)

In [47]:
res1

tensor([4., 5., 3.])

In [48]:
mask.dtype

torch.bool

In [49]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [50]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [52]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]